name: CI Workflow

on:
  push:
  pull_request:

jobs:
  # JOB lint
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ci_lab
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Flake8
        run: pip install flake8
      - name: Run Flake8 Linting
        run: flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

  # JOB 2 test
  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensures tests only run if code passes linting
    defaults:
      run:
        working-directory: ci_lab
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests with Pytest
        run: pytest --cov=src --cov-report=term-missing

  # JOB coverage
  coverage:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ci_lab
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Check Coverage Threshold
        run: pytest --cov=src --cov-fail-under=80
        
